### ISSUE TITLE
Use the tileset on the generate-metadata tool

### ISSUE THREAD

**Issue by francois2metz** [openmaptiles/openmaptiles-tools#148]
After #145, the only user of `openmaptiles/consts.py` is `bin/generate-metadata`. What do you think of adding a new argument `tileset` and parse it to generate the metadata instead of using environment variables and hard-coded values?

**Comment by nyurik** [comment]
I think that would be good to move these types of settings to the tileset file.  
@eva-j @MartinMikita @daliborjanak  can you think of any params that should be build-time settings rather than part of the tileset file?

P.S. `PIXEL_SCALE` is used in sqltomvt

**Comment by nyurik** [comment]
I think we can now address this issue because we have the new `mbtiles-tools` utility ([docs](https://github.com/openmaptiles/openmaptiles-tools/blob/master/bin/mbtiles-tools#L3)). I think it can do much more than `generate-metadata` tool, including the updates of the mbtiles directly from the layers.

**Comment by francois2metz** [comment]
So should the generate-metadata tools be removed?

**Comment by nyurik** [comment]
@francois2metz once I get https://github.com/openmaptiles/openmaptiles/pull/893 merged (it needs a few minor cleanup things first), yes.

**Comment by francois2metz** [comment]
I believe it was fixed.
