### ISSUE TITLE
Publish openmaptiles-tools to PyPI

### ISSUE THREAD

**Issue by lukasmartinelli** [openmaptiles/openmaptiles-tools#2]

**Comment by lukasmartinelli** [comment]
Can we republish the latest version? Or give me publish rights on PyPI to `lukasmartinelli`.

**Comment by klokan** [comment]
Please republish yourself: https://pypi.python.org/pypi/openmaptiles-tools

Klokantech is owner of the package.
You are set as maintainer, @lukasmartinelli

**Comment by lukasmartinelli** [comment]
Perfect thanks. v0.2 published.

**Comment by ImreSamu** [comment]
@lukasmartinelli 

>Perfect thanks. v0.2 published.

:laughing: :   Sorry, this is my fault because I have not mentioned before , 
but if possible, 
please keep the `tags` with synchronous the VERSION file ... 
* with https://github.com/openmaptiles/openmaptiles-tools/blob/master/VERSION.

I am using this VERSION file with the [`make build`](https://github.com/openmaptiles/openmaptiles-tools/blob/master/Makefile#L29) ,  and need increase because I want different docker images for development and testing ...  
( and sometimes I have committed  :(   )

next time
*  probably I will add a `0.3Dev`  or similar tags ...  and you have to set to the final : `0.3` before release and tagging ..  https://github.com/openmaptiles/openmaptiles-tools/tags

**Comment by klokan** [comment]
@ImreSamu - please read the version from latest GIT tag when you do make build and need the version.

VERSION file should be removed, if possible, please...

See:
http://stackoverflow.com/questions/1404796/how-to-get-the-latest-tag-name-in-current-branch-in-git or alternatives.

**Comment by ImreSamu** [comment]
@klokan 

I am thinking about this ...   
 
>VERSION file should be removed, if possible, please...

my problem was that in the earlier version - the version `0.1`  was hard coded to the `setup.py` , 
and sometimes I forget to modify .... 
So  I have just moved this to the external config file ...  

the original `setup.py`  was :  
```py
setup(
     name='openmaptiles-tools',
     version='0.1',
     packages=['openmaptiles'],
```
https://github.com/openmaptiles/openmaptiles-tools/commit/6fbf4669e0d1aaa1c796102e9e2fe3f0f1c47c9c#diff-2eeaed663bd0d25b7e608891384b7298R5

So I modified to pick up the version info  from external file ...  
```py
setup(
    name='openmaptiles-tools',
    version=open('VERSION').read(),
    packages=['openmaptiles'],
```

> please read the version from latest GIT tag when you do make build and need the version.

it is very complex .. because sometimes I don't have GIT  ..

for example:    
* If I want install the python package from he source code release (zip, tar.gz) 
    *   then I  should have detect the GIT tag from the directory name  :( 

```bash
wget https://github.com/openmaptiles/openmaptiles-tools/archive/v0.2.zip
unzip v0.2.zip
```

```log
$ unzip v0.2.zip
Archive:  v0.2.zip
8000f1894e681f548fe1bb7285e7264e11e5b3c1
   creating: openmaptiles-tools-0.2/
  inflating: openmaptiles-tools-0.2/.gitignore  
  inflating: openmaptiles-tools-0.2/.travis.yml  
  inflating: openmaptiles-tools-0.2/Dockerfile  
  inflating: openmaptiles-tools-0.2/Dockerfile.py27  
  inflating: openmaptiles-tools-0.2/LICENSE  
  inflating: openmaptiles-tools-0.2/Makefile  
  inflating: openmaptiles-tools-0.2/README.md  
 extracting: openmaptiles-tools-0.2/VERSION  
   creating: openmaptiles-tools-0.2/bin/
  inflating: openmaptiles-tools-0.2/bin/generate-doc  
  inflating: openmaptiles-tools-0.2/bin/generate-etlgraph  
  inflating: openmaptiles-tools-0.2/bin/generate-imposm3  
  inflating: openmaptiles-tools-0.2/bin/generate-mapping-graph  
  inflating: openmaptiles-tools-0.2/bin/generate-metadata  
  inflating: openmaptiles-tools-0.2/bin/generate-sql  
  inflating: openmaptiles-tools-0.2/bin/generate-sqlquery  
  inflating: openmaptiles-tools-0.2/bin/generate-tm2source  
  inflating: openmaptiles-tools-0.2/checklist.chk  
   creating: openmaptiles-tools-0.2/openmaptiles/
 extracting: openmaptiles-tools-0.2/openmaptiles/__init__.py  
  inflating: openmaptiles-tools-0.2/openmaptiles/diagram.py  
  inflating: openmaptiles-tools-0.2/openmaptiles/docs.py  
  inflating: openmaptiles-tools-0.2/openmaptiles/imposm.py  
  inflating: openmaptiles-tools-0.2/openmaptiles/sql.py  
  inflating: openmaptiles-tools-0.2/openmaptiles/tileset.py  
  inflating: openmaptiles-tools-0.2/openmaptiles/tmsource.py  
  inflating: openmaptiles-tools-0.2/setup.py  
   creating: openmaptiles-tools-0.2/testlayers/
   creating: openmaptiles-tools-0.2/testlayers/housenumber/
  inflating: openmaptiles-tools-0.2/testlayers/housenumber/housenumber.yaml  
  inflating: openmaptiles-tools-0.2/testlayers/housenumber/housenumber_centroid.sql  
  inflating: openmaptiles-tools-0.2/testlayers/housenumber/layer.sql  
  inflating: openmaptiles-tools-0.2/testlayers/housenumber/mapping.yaml  
  inflating: openmaptiles-tools-0.2/testmaptiles.yaml  
```

**Comment by ImreSamu** [comment]
@klokan 

I know this is not a critical problem ... 

but what is you opinion about the git hooks -  based solution   ?  
So the VERSION file  or a `setup.py` will be automatically updated/overwritten   -  based on he Github tags change!    

As I see this is a similar  problem :  
see:  http://stackoverflow.com/questions/8418071/is-there-a-way-to-check-that-a-git-tag-matches-the-content-of-the-corresponding?noredirect=1&lq=1
