### ISSUE TITLE
Postgis image build fails due to mapnik-german-l10n

### ISSUE THREAD

**Issue by lazaa32** [openmaptiles/openmaptiles-tools#391]
`make build-postgis` generates following error:
```
+ cd mapnik-german-l10n
+ make
...
...
./gen_osml10n_extension.sh /usr/share/postgresql/9.6/extension 2.5.9
Trying to download country_grid.sql.gz from nominatim.org... 
gzip: stdin: not in gzip format
failed.
make: *** [Makefile:60: osml10n--2.5.9.sql] Error 1
```
This is a problematic part in https://github.com/giggls/mapnik-german-l10n repo:
https://github.com/giggls/mapnik-german-l10n/blob/master/gen_osml10n_extension.sh#L23

```
curl -s http://www.nominatim.org/data/country_grid.sql.gz |gzip -d >country_osm_grid.sql
gzip: stdin: not in gzip format
```

```
curl -s http://www.nominatim.org/data/country_grid.sql.gz
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>
```
```
wget http://www.nominatim.org/data/country_grid.sql.gz
```
Works fine.

It seems that there was some modification done and it needs to be fixed upstream.

**Comment by lazaa32** [comment]
Fix PR created
https://github.com/giggls/mapnik-german-l10n/pull/59

**Comment by nyurik** [comment]
Every time I see an issue like this I keep wondering if it would be possible to do all of it in pure sql, and possibly submit a pr to postgis to add the needed functionality...

**Comment by zstadler** [comment]
I'm trying to create a PR to [make $PGPORT work in OMT](https://github.com/openmaptiles/openmaptiles/issues/1354#issuecomment-1041817719)
As it looks now, there is also needs a minor change in [initdb-postgis.sh](https://github.com/openmaptiles/openmaptiles-tools/blob/master/docker/postgis/initdb-postgis.sh).

I cannot check that change because the built of the `openmaptiles/postgis` image is broken.
The release of the fix in https://github.com/giggls/mapnik-german-l10n/pull/59 is stuck because the [CI for the mapnik-german-l10n repository is also broken](https://github.com/giggls/mapnik-german-l10n/actions).
There was no progress there since 1 Dec 2021.

@nyurik, @lazaa32,
Could you look into ways of making the `openmaptiles/postgis` image build again?

**Comment by TomPohys** [comment]
We are now using https://github.com/openmaptiles/mapnik-german-l10n.git (https://github.com/openmaptiles/openmaptiles-tools/blob/master/docker/postgis/Dockerfile#L23). Can you make PR into this fork? Thanks

**Comment by zstadler** [comment]
Oooops... I forgot to `git fetch` ...

**Comment by TomPohys** [comment]
No problem :-) 

Lets close this because the PostGIS image using OpenMapTiles fork works.
